### ISSUE TITLE
Guidance and/or permission to use the Solidity code in this repository

### ISSUE THREAD

**Issue by killergerbah** [AmbireTech/signature-validator#10]
Hi, and thank you for this project. It has saved me a lot of time.

I would like to extend an existing Java-based, open source web3 project with the functionality in this repository using the same smart contract. However, given that the code is unlicensed, my understanding is that I have no license to use the code in another open source project. If this understanding is correct, then giving this code an open source license would resolve this problem. Do you have any thoughts on this?

Thank you!

**Comment by Ivshti** [comment]
hey, thanks for the feedback

afaik you don't need license to use the bytecode, and that's all you need. Also since it's an EIP, it's public domain. If you'd like, feel free to PR a LICENSE file for MIT or UNLICENSE.

You need the compiled solidity bytecode to do an eth_call the same way that the JS is doing it

Good luck!

**Comment by killergerbah** [comment]
Thanks for your reply. I did not know that the original Solidity code came from an EIP and is public domain. Although it is slightly different from what you suggested, can I propose simplify modifying the SPDX identifier of the Solidity files to be `CC0-1.0`? As mentioned above and based on my own research `UNLICENSED` has the opposite meaning of public domain, unfortunately.

**Comment by Ivshti** [comment]
Done, the license identifier has been updated to CC0-1.0 now
